author:leezeeyee   
date:2021/5/12

In [1]:
import numpy as np

## Gram-Schmidt process

In [9]:
def proj(U,V):
    '''
    computer the projection of vector $V$ on the direction of $U$ 
    U and V should be same dimension
    '''
    if U.shape != V.shape:
        raise Exception('not in same dimension')
    return np.dot(U,V)*U/np.dot(U,U)

In [11]:
proj(np.array([3,4]),np.array([3,2]))

array([2.04, 2.72])

In [50]:
def gram_schmidt(A):
    U=np.copy(A)
    for col in range(A.shape[1]):
        #print(A[:,col]) 
        for i in range(col):
            # now the u is already guiyi
            U[:,col]-=np.dot(U[:,i],A[:,col])*U[:,i]#proj(U[:,i],A[:,col]) 
        U[:,col]/=np.sqrt(np.dot(U[:,col],U[:,col]))
    return U
            


In [51]:
res=gram_schmidt(np.random.rand(5,3))

In [52]:
res

array([[ 0.11989545,  0.06535308,  0.74256348],
       [ 0.62500627,  0.69793329,  0.06400778],
       [ 0.46046477, -0.05589415, -0.60180545],
       [ 0.49599204, -0.67357036,  0.09707424],
       [ 0.37007613, -0.22758937,  0.27001718]])

In [53]:
for col in range(res.shape[1]):
    print(np.dot(res[:,col],res[:,2]))

-4.0245584642661925e-16
4.163336342344337e-16
1.0


## QR decomposition

In [61]:
A=np.random.rand(5,3)
Q=gram_schmidt(A)
R=np.zeros([A.shape[1],A.shape[1]])
for j in range(A.shape[1]):
    for i in range(j+1):
        R[i][j]=np.dot(Q[:,i],A[:,j])


In [62]:
R

array([[1.52440414, 1.40610236, 1.2522591 ],
       [0.        , 0.3136897 , 0.46566284],
       [0.        , 0.        , 0.49586757]])

In [65]:
np.dot(Q,R)

array([[0.27310235, 0.32981504, 0.76491029],
       [0.65152826, 0.42815919, 0.4592476 ],
       [0.78537878, 0.87165847, 0.80440021],
       [0.59805715, 0.37117242, 0.11793651],
       [0.9220856 , 0.94120633, 0.75757148]])

In [64]:
A

array([[0.27310235, 0.32981504, 0.76491029],
       [0.65152826, 0.42815919, 0.4592476 ],
       [0.78537878, 0.87165847, 0.80440021],
       [0.59805715, 0.37117242, 0.11793651],
       [0.9220856 , 0.94120633, 0.75757148]])